### ISSUE TITLE
Deobfuscation didn't work well

### ISSUE THREAD

**Issue by pat-ford** [java-deobfuscator/deobfuscator#216]
Hi All;
 I have a dexguarded apk that doesn't seem to do much when passed through your program.
Process I used
1) unzip apk (com.parental.control.v4-dexguarded_apk.zip)
2) dex2jar classes.dex (classes_dex2jar_jar.zip)
3) not much joy in the output (deobfused_jar.zip)

I know Android isn't your target just thought I'd share.
Pat
    
    Thank you!
[deobfused_jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/1782495/deobfused_jar.zip)
[classes_dex2jar_jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/1782497/classes_dex2jar_jar.zip)
[com.parental.control.v4-dexguarded_apk.zip](https://github.com/java-deobfuscator/deobfuscator/files/1782498/com.parental.control.v4-dexguarded_apk.zip)

**Comment by pat-ford** [comment]
BTW that apk is malware, so don't run it on a phone

**Comment by ThisTestUser** [comment]
[DexGuardSampleDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/1799721/DexGuardSampleDeob.zip)
Decrypted some strings here, but since its an android file and the dex2jar is not perfect, its not possible to remove everything. I highly suggest you use bytecode viewer to decompile it.
