### ISSUE TITLE
Stringer failed deobfuscation

### ISSUE THREAD

**Issue by TheNamedMeFilip** [java-deobfuscator/deobfuscator#282]
Hello, i tried to deobfuscated this FREE spigot plugin MiniAnni (https://www.spigotmc.org/resources/new-miniannihilation.59326/) and i failed. It's only partly deobfuscated. Can you help or deobfuscate it for me?

Download: <redacted>

**Comment by fikawka** [comment]
[deobforfree.zip](https://github.com/java-deobfuscator/deobfuscator/files/2250537/deobforfree.zip)

Slightly cleared, I could not because I had evil versions of java
use transformers: stringer.v3.stringencryptiontransformer
stringer.v3.resourceencryptiontransformer
stringer.v3.invokedynamictransformer

**Comment by TheNamedMeFilip** [comment]
Very much thanks for helping me

**Comment by TheNamedMeFilip** [comment]
How did you do that?
