### ISSUE TITLE
String obfuscated weirdly

### ISSUE THREAD

**Issue by Mod-Mat-K** [java-deobfuscator/deobfuscator#302]
Any idea how to reverse this kind of obfuscation?
https://i.imgur.com/oe4wnkG.png

`UA.iiiiiiiIiIII.setText("Dpe()e,#Zyc msuh<\u0004\u0003S\u0012x\u000ed},xe*nhu0TpOO4)Z7\u0014\u001f\u001dY");`

JAR has already been deobfuscated once with the allatori transformer

Original jar: https://mega.nz/#!EiAg3ASI!pMhJ0-YE7gz6UrGY6kM3_yb_EpQKFqesB6DV53mxpVk

**Comment by Janmm14** [comment]
This looks like your deobfuscation did not lead to success, However I don't know why it failed, it definitely looks like allatori.

**Comment by ThisTestUser** [comment]
[inputDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2354799/inputDeob.zip)
You may have renamed the classes, which could have broken the decryptor.
Another reason the allatori transformer might error is because javavm can't handle the exceptions Allatori uses to generate the stacktraces.
Otherwise, use this deobfuscator.jar: https://github.com/ThisTestUser/deobfuscator/releases
And select allatori.StringEncryptionTransformer.

**Comment by Mod-Mat-K** [comment]
Apologies for late response, will test again now.

**Comment by l89669** [comment]
See [this](https://github.com/l89669/AntiObfuscateTools/blob/master/DSDCracker.java) for allatori's newest string obfuscate method and its' solution.
