### ISSUE TITLE
Can't deobf this jar.

### ISSUE THREAD

**Issue by Levelheader** [java-deobfuscator/deobfuscator#305]
I can't figure out how this jar is obfuscated, or the strings. Something tells me my decompiler isn't showing a majority of the code in here. As well as the strings being obfuscated with something custom. If you could please reverse the string obfuscation as well as whatever is making the code so discombobulated, that would be great.

THE CODE IS LOCATED IN META-INF/byCCBlueX/LiquidBounce

[LiquidBounce1.8.9-b54.zip](https://github.com/java-deobfuscator/deobfuscator/files/2398483/LiquidBounce1.8.9-b54.zip)

**Comment by Janmm14** [comment]
You tried using Krakatau as decompiler?

**Comment by Levelheader** [comment]
It breaks Krakatau. So that's a negative.

**Comment by superblaubeere27** [comment]
They are using their own obfuscator

**Comment by ItzSomebody** [comment]
Since this got replied to and I got a notification for it, I guess I might as well throw in my two cents.

The reason why some decompilers crash/show inaccurate code is because the developers use some [of these](https://github.com/Janmm14/decompiler-vulnerabilities-and-bugs/tree/master/DVB).

> It breaks Krakatau. So that's a negative.

No it doesn't?

```java
    private static String \u180a\u1a79\u21ae\u0b07\u1417\u1281\u0903\u2264\u18ec\u0ee8(CharSequence a, CharSequence a0)
    {
        try
        {
        }
        catch(javax.crypto.BadPaddingException a1)
        {
            javax.crypto.BadPaddingException a2 = a1;
            while(true)
            {
                try
                {
                    throw a2;
                }
                catch(Throwable a3)
                {
                    try
                    {
                        throw a3;
                    }
                    catch(javax.crypto.BadPaddingException a4)
                    {
                        a2 = a4;
                    }
                }
            }
        }
        char[] a5 = a.toString().toCharArray();
        " ".toCharArray();
        char[] a6 = a0.toString().toCharArray();
        char[] a7 = new char[a5.length];
        int i = 0;
        while(i < a5.length)
        {
            int i0 = (char)((boolean)a5[i] ^ (boolean)a6[i % a6.length]);
            a7[i] = (char)i0;
            i = i + 1;
        }
        "   ".length();
        return new String(a7);
    }
```

Let's move onto the string encryption. An example I found just by poking around is:

```jasmin
L48:    ldc 'insertsomeencryptedstringorwhateverhere' 
L50:    ldc 'anotherstring' 
L52:    iconst_0 ; not used
L53:    pop 
L54:    invokestatic Method META-INF/byCCBlueX/LiquidBounce/llllll1l$2 '\u1925\u2007\u20e7\u190c\u222e\u0ce4' (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; 
```

Another couple of samples I found essentially follow the same pattern but change the method signature slightly. For example, `(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;` so it's pretty straightforward as to how you can tackle that. You could probably just modify [this](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/stringer/v3/StringEncryptionTransformer.java) to decrypt these strings.

Also, there's a lot of trash in the bytecode like this:
```jasmin
L57:    ldc '   ' 
L59:    aconst_null 
L60:    invokevirtual Method java/lang/String equals (Ljava/lang/Object;)Z 
L63:    ldc '  ' 
L65:    invokevirtual Method java/lang/String isEmpty ()Z 
L68:    pop2 
```

and
```jasmin
L80:    aconst_null 
L81:    aconst_null 
L82:    pop 
L83:    astore_2 
```

so you might have to write a transformer to optimize these patterns away. These are pretty simple and should be no match for Krakatau.

**Comment by Janmm14** [comment]
@ItzSomebody The number obfuscation transformer is already there, a smoke transformer.

**Comment by superblaubeere27** [comment]
@Janmm14 Just use the ConstantFolder. This will revert this
