### ISSUE TITLE
invokedynamic inline failed

### ISSUE THREAD

**Issue by thistempuser** [java-deobfuscator/deobfuscator#342]
Cannot deobfuscate this file
tried every transformer related to invokedynamic, still cant remove the invokedynamic instructions
[program.zip](https://github.com/java-deobfuscator/deobfuscator/files/2695020/program.zip)

**Comment by ThisTestUser** [comment]
[programDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2696863/programDeob.zip)

**Comment by thistempuser** [comment]
[program-original.zip](https://github.com/java-deobfuscator/deobfuscator/files/2697530/program-original.zip)
Thanks for your work! Here's the original program, btw, could you please give me the configuration you used to deobfuscate this?
I'm using the release from your fork, still have no idea how you deobfuscated this program.

**Comment by ThisTestUser** [comment]
[programDeob.zip](https://github.com/java-deobfuscator/deobfuscator/files/2700637/programDeob.zip)
First, you need to attach 3 libraries:
PlaceHolderAPI
BetonQuest
AuthMe
Secondly, you need to modify the deobfuscator a bit, because this is a custom obfuscator.
[jvmmethodprovider.zip](https://github.com/java-deobfuscator/deobfuscator/files/2700662/jvmmethodprovider.zip)
[stringer.invokedynamictransformer.zip](https://github.com/java-deobfuscator/deobfuscator/files/2700667/stringer.invokedynamictransformer.zip)
The modified class files are below, replace the old class files with this one and you should be able to deobfuscate the file.
Note that you must use stringer.invokedynamictransformer, stringer.hideaccesstransformer, and then allatori.stringencryptiontransformer.

**Comment by thistempuser** [comment]
Thanks again for your help. With these file now I can deobfuscate this program by myself.
