### ISSUE TITLE
Unknown obfuscator not deobfuscate

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator#511]
jar for deob: https://mega.nz/#!CqZxVIIY!UmlGGo6Q50AV56OdK42OrQFPv8ZXapon2ns8tZm1uxg

**Comment by ItzSomebody** [comment]
Looks like ZKM and maybe Allatori.

**Comment by lolka13373** [comment]
@ItzSomebody Can you remove the obfuscation? I want to know how this plugin works.

**Comment by febryanasaperdana** [comment]
> @ItzSomebody Can you remove the obfuscation? I want to know how this plugin works.

If the plugin you mentioned is not yours, and the true/respective owner of the plugin protects it, then it means you are "not allowed" to peek into the plugin internals (source code, logic/flow, etc.). That's why people are hesitated to help.
Most of people here are not doing deobfuscation for others. But we may give you a constructive feedback on what to do next/ Just do it on your own! And if you'd rather give up, contact the appropriate owner/developer of the plugin. But I doubt you'll be not given any opportunity to check it, though.

**Comment by ItzSomebody** [comment]
Closing since this is relatively old and for the reasons @febryanasaperdana provided.
