### ISSUE TITLE
ZKM trouble

### ISSUE THREAD

**Issue by MoofMonkey** [java-deobfuscator/deobfuscator#54]
http://pastebin.com/LdQCR03L
JAR: http://rgho.st/6N6Jz4PcB
Password: link for this issue

**Comment by MoofMonkey** [comment]
DoubleTrouble!
http://pastebin.com/j071bdck
JAR: http://rgho.st/7DFPC2q9d
Password: link for this issue

**Comment by MoofMonkey** [comment]
This is lambda trouble. All repeats... >_<

**Comment by Janmm14** [comment]
Did you tried reversing string and reflection obfuscation transformation?

**Comment by MoofMonkey** [comment]
Yes, tried. Fail...
And comment of author - https://github.com/java-deobfuscator/deobfuscator/issues/52#issuecomment-238092597

**Comment by MoofMonkey** [comment]
Author @samczsun is die?

**Comment by samczsun** [comment]
Maybe the author is on vacation and wants to take a break for a week or two 🤔

**Comment by Eyremba** [comment]
> UPD: This is eval for Zelix KlassMaster. Maybe learn it?

Just funny. :D 

You can not "learn" from the eval. version of ZKM because it does only light obfuscation. For example, the eval. version of ZKM does only flow-obfuscate 1 or 2 methods in each class file.

(On the zkm homepage: "The evaluation version will flow obfuscate only one or two methods in each class.")

So you can not really learn from it.

**Comment by Janmm14** [comment]
But if zkm trial still applies all its algorithms, having just enough classes will reveal everything.

**Comment by Eyremba** [comment]
> @Eyremba But if zkm trial still applies all its algorithms, having just enough classes will reveal everything.

Not really, the full version of Zelix goes much deeper.
