### ISSUE TITLE
No one decompilers not working on this obfuscation

### ISSUE THREAD

**Issue by Xed0sS** [java-deobfuscator/deobfuscator#600]
Wtf, why no one decompiler doesn't works on this obfuscation? JByte Mod, Threadtear, ByteCodeViewer, JD Gui?

JAR: https://www.upload.ee/files/12042615/minecraft.jar.html

**Comment by nedogimov** [comment]
> Wtf, why no one decompiler doesn't works on this obfuscation? JByte Mod, Threadtear, ByteCodeViewer, JD Gui?
> 
> JAR: https://www.upload.ee/files/12042615/minecraft.jar.html

Cristalix use their obfuscator. CFR can decompile this, but no deobfuscate

**Comment by Janmm14** [comment]
krakatau should be able to decompile nearly everything

**Comment by CertainLach** [comment]
There is no point in adding those tricks deobfuscation into public projects, because this obfuscator is highly specialized, and is used only on a dozen jars in world

No one, expcept one who trying to reverse our code will gain something from it

We have no plans on opensourcing/selling them either.
