### ISSUE TITLE
omggggg, impossible deobf jar file!

### ISSUE THREAD

**Issue by SimpleMoletu** [java-deobfuscator/deobfuscator#634]
impossible to deobf
Link: http://www.mediafire.com/file/ins3k0q0n7muc29/file
pls help

**Comment by Enteerman** [comment]
Lol, this repo needs collaborators that close issues like this

**Comment by Enteerman** [comment]
This is not related to this project. Although the program is named "deobfuscator", deobfuscating a specific program is illegal, and no one will care to deobfuscate your program. Please close this.

**Comment by febryanasaperdana** [comment]
> This is not related to this project. Although the program is named "deobfuscator", deobfuscating a specific program is illegal, and no one will care to deobfuscate your program. Please close this.

Very true. It's sad that this project's issue page is flooded with many deobfuscation requests, instead of reporting bugs/errors on the deobfuscator. Most of them are trying to deobfsucate a premium plugin, license file, etc. If these file/code is protected with legal protection, then anyone who requested the deobfuscation as well as those who are helping to deobfuscate will get in trouble. Most people are not even trying to deobfuscate on their own and just spam a request for deobfuscation. Sad, but indeed it's true.
