### ISSUE TITLE
Allatori string decryption will fail when encrypted multiple times

### ISSUE THREAD

**Issue by barrN** [java-deobfuscator/deobfuscator#645]
Background:
1. Allatori string encryption was applied 3 times (or more).
2. It appears the same method is used multiple times for each decryption function (example provided below).
3. doesn't result in any error.

Consider the following:
We have a standard Allatori decryption call:
`decrypt_method_1("foobar", 1337)`

This is the failure point:
`decrypt_method_1(decrypt_method_2(decrypt_method_1("foobar", 1337), 2555, 4444))`

On each pass, the transformer will remove the decryption method, so when we first decrypt method_1, it will be removed and thus unavailable for the third and final decryption.

I can provide a jar, but not publicly.

**Comment by Enteerman** [comment]
Which transformer did you use? (There are two)

**Comment by Janmm14** [comment]
How does it fail? Does it only decrypt one layer?

**Comment by barrN** [comment]
the process is to run the transformer on a deobfuscated file for each layer, however once the decryption methods overlap:

**decrypt_method_1**(decrypt_method_2(**decrypt_method_1**("foobar", 1337), 2555, 4444))

It will not decrypt the final layer (being decrypt_method_1), as that method had already been removed from an earlier transformation. 

Transformer ran was the latest one, specifically: StringEncryptionTransformer.java (updated 3 months ago).

**Comment by ItzSomebody** [comment]
So I saw this earlier but had to run before I had a chance to reply due to work and forgot to reply. The issue here is that the deobfuscator literally removes the decryptor MethdNode. The responsible line in the Alllatori MethodExecutor transformer can be found at https://github.com/java-deobfuscator/deobfuscator/blob/a4df544604ef96fbe3d5052ebb3d56c79c20ff5d/src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java#L162.

While I'm not really sure if this is really an issue (you can just modify the transformer to leave the decryptors), I do think this might call for splitting the "cleanup" portion of the transformer into a seperate transformer (similar to how the JavaVM transformers for Stringer are done.)

**Comment by Enteerman** [comment]
Possible solution: Check for invoke instructions before removing the methodnode. This could be set as a flag in config.

**Comment by Janmm14** [comment]
In case the automatic still-used detection fails, you can set cleanup to false in the config.yml when using the deobfuscator via cli.

```yml
transformers:
  - allatori.StringEncryptionTransformer:
      cleanup: false
```
