### ISSUE TITLE
infinity loading

### ISSUE THREAD

**Issue by sysysysy242** [java-deobfuscator/deobfuscator#650]
this infinty load 
![image](https://user-images.githubusercontent.com/45331186/96026875-62f37c80-0e57-11eb-915b-6cf9a65657e7.png)

How to fix ?

**Comment by sysysysy242** [comment]
Update : 
![image](https://user-images.githubusercontent.com/45331186/96030280-1b232400-0e5c-11eb-80b4-f8f3c6f31f37.png)
This don't work

**Comment by Janmm14** [comment]
The error in the console is there, because you did not add rt.jar to the path list of the config.
```yaml
path:
 - "C:/path/to/rt.jar"
```

Some transformers might take some time to complete, as this project is simulating java execution inside of java.

Package, class, method and variable names are not restored by StringTransformers. They decrypt string constants of the actual code (eg. `"This is a string"`).

Look at transformers in the minecraft package for attempts to bring back class, method and variable names of minecraft classes.

Additionally, don't use JAD. Use BytecodeViewer or Luyten, they produce better java code, have less exploits and are more accurate.

The most accurate decompiler available is Krakatau. Pair it with BytecodeViewer as GUI and PyPy as Python executable.
