### ISSUE TITLE
Deobfuscation Request (Malware)

### ISSUE THREAD

**Issue by Deletus1337** [java-deobfuscator/deobfuscator#651]
Hello this is a remote access tool and a chrome password stealer. Can you deobfuscate it please?

https://www.mediafire.com/file/ifp6k3umhanftix/Malware_%2528DO_NOT_RUN%2529.zip/file

**Comment by Enteerman** [comment]
Not a place for deobfuscation requests.

**Comment by bytechef** [comment]
I ran it 😎

**Comment by Janmm14** [comment]
@Enteerman
I think deobfuscation requests are similar to providing a sample - as long as the redistribution does not violate copyright.

@Deletus1337 
Please show what you have tried and we might fix errors occuring during your deobfuscation attempts.

**Comment by Enteerman** [comment]
It should be a feature request of said obfuscation method instead of just asking for deobfuscation. Even if it is a malware I do not see any point in helping deobfuscating the program other than for improving. I will keep this issue closed until @Deletus1337 provides more information (errors that may occur, failed attempts, configuration file, detect output)
