### ISSUE TITLE
Request for add new transformer

### ISSUE THREAD

**Issue by BOBsonic459** [java-deobfuscator/deobfuscator#697]

**Comment by BOBsonic459** [comment]
??

**Comment by BOBsonic459** [comment]
<! -
Hi ^^, I ask you if possible to add the transformers of Mixins to your java deobfuscator: https://github.com/SpongePowered/Mixin, that would be very useful, thank you for answering me please

-BOBsonic576
->

**Comment by Janmm14** [comment]
Mixins are not obfuscation. There is no need for deobfuscation.

**Comment by BOBsonic459** [comment]
however mixin mods are obfuscated, and there are package obfuscation in mixin code

**Comment by Janmm14** [comment]
If and only IF you have the right to share the mixin mod: Can you provide a sample of an obfuscated mixin mod?

**Comment by BOBsonic459** [comment]
Okay, link of the mod : https://fromsmash.com/O55ecfcsiy-ct

**Comment by Janmm14** [comment]
@BOBsonic459 **You do NOT have the rights to share this mod**. Not hard to find out in mcmod.info it says:

> Toute distribution ou reproduction même partielle sans l'accord de l'équipe de développement de Paladium est strictment interdite.

Google translate is my friend and it clearly says that distribution is not allowed without agreement of paladium development team.
Please delete the download link from your message.

A little hint for you though:
You can try the existing minecraft transformers to rename some fields and methods used in this mod, but otherwise there is nothing to deobfuscate.
Class name, method name and field name obfuscation is not reversible otherwise.

**Comment by fee1-dead** [comment]
I don't have permissions to remove the link, but I will close this so it doesn't appear on Issues (unless you click closed issuse)
