### ISSUE TITLE
ClassGuard supported how?

### ISSUE THREAD

**Issue by Python-22** [java-deobfuscator/deobfuscator#723]
I just want to know how exactly is ClassGuard supported? Since there isnt any transformers for it so is there alternative transformers to use?

**Comment by ItzSomebody** [comment]
There is a transformer. [https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/classguard/EncryptionTransformer.java](https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/transformers/classguard/EncryptionTransformer.java)

If I recall correctly, the transformer is outdated but Classguard's protection scheme hasn't changed (though, it's been at least a year since I have checked).  Classguard's protection scheme uses hardcoded keys, so extracting the keys and updating the deobfuscator should be pretty easy if you have some experience reversing native binaries.
