### ISSUE TITLE
Bozar obfuscator trouble

### ISSUE THREAD

**Issue by LuckerCracker** [java-deobfuscator/deobfuscator#774]
None of the transformers can deobfuscate him.

I have attached an obfuscated file.
[govno.zip](https://github.com/java-deobfuscator/deobfuscator/files/6604673/govno.zip)

**Comment by Janmm14** [comment]
Delete class in default package manually first.

Obfuscation has some tricks which requires some upgrades to constantfolder.
Then one should write a string transformer similar to the skidsuite2 approach with an analyzer, (I suggest not bothering with removal first and just use pop and then insert ldc result)
Then replace MethodType ldc at method start with string ldc so you can watch it more decompilers.
Some transformer like [this](https://github.com/Janmm14/deobfuscator/blob/caesium/src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/UselessOperationTransformer.java) can help making stuff easier to read.

Some flow obfuscation will still be nasty afterwards.

The result I got is the just 17kb and no more 116kb.

Due to me not wanting to support bypassing (clientside) anticheats, I will not post the result jar here.
Code is not malicious, client mod is safe to use.
