### ISSUE TITLE
What's this & is there an allatori timestamp remover?

### ISSUE THREAD

**Issue by huzpsb** [java-deobfuscator/deobfuscator#787]
Is there a transformer that can remove allatori's date control?
It's injected into init method of every classes,as is shown below.
![snap1](https://user-images.githubusercontent.com/41772578/124419307-caf44500-dd8f-11eb-9e08-c6691b6abc57.png)

Also,I wanna know if every invoke was turned into reflect,as shown below,
how can i deal with it?
![snap2](https://user-images.githubusercontent.com/41772578/124419599-65548880-dd90-11eb-8a80-154a3ebcbef6.png)
I tried just ignore them,but when i was normalizing method names,they just turned into ****.
Can anybody help me pls?Tks!

(Attached will you find a zip containing the jar which I am trying to deobfuscate.)
[files.zip](https://github.com/java-deobfuscator/deobfuscator/files/6761810/files.zip)

**Comment by ThisTestUser** [comment]
For the expiring date thing you could just set the long value to a very high number if you wanted to get around it, but otherwise there's no transformer to remove it (it wouldn't be hard to make though). For the reflection calls I think you have to find an obfuscator that can rename classes while handling reflection calls, but otherwise there wouldn't be an easy way to convert them back to invoke calls.
