### ISSUE TITLE
Help with detecting an obfuscator 

### ISSUE THREAD

**Issue by IamSanjid** [java-deobfuscator/deobfuscator#793]
The detector couldn't give me a result.
When I opened it in a decompiler and checked the Main function, I see a lot of try catches, and saw a big switch statement
saw weird class names such as `ji.wO.Yf0`, `B00.xQ`, `Z60.P5`.
[PokeMMO.zip](https://github.com/java-deobfuscator/deobfuscator/files/6794142/PokeMMO.zip)

**Comment by Janmm14** [comment]
The deobfuscator project is not created to fix weird class names. In 99% of cases, class name changes cannot be automatically reversed. Mthod and field names cannot be reversed in 100% of cases.

PokeMMO uses JNI - java native interface - a lot. That is another level of obfuscation this project does not aim for.

Apart from that, it seems like there is just the previously explained identifier (class, method, field name) obfusction present and some of the libraries like gdx and tweenengine are not obfuscated.

**Comment by IamSanjid** [comment]
Ah @Janmm14 how can I find out how it uses the JNI?

**Comment by ItzSomebody** [comment]
@IamSanjid:  You would have to inspect the program yourself (whether that be via a decompiler, disassembler, hex editor, etc.) and from that determine whether or not the program invokes native subroutines through the JNI (usually somewhat easy to tell due to certain methods having the `ACC_NATIVE` flag or whatever it's called).

I'll close this now as it doesn't seem like this is within this project's scope, but feel free to reply if I missed anything.
