### ISSUE TITLE
So i were deobfuscating file and this happened

### ISSUE THREAD

**Issue by f4r2** [java-deobfuscator/deobfuscator#953]
![image](https://user-images.githubusercontent.com/55927996/216695037-323be09d-7759-4966-89bf-e42bb3fb45d3.png)
Is this normal? 
Used transformers:
- com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
- com.javadeobfuscator.deobfuscator.transformers.zelix.string.EnhancedStringEncryptionTransformer
- com.javadeobfuscator.deobfuscator.transformers.smoke.NumberObfuscationTransformer

**Comment by Janmm14** [comment]
This happens when you use transformers in a sub-package of the obfuscator, because they use another way of simulated execution (like `zelix.string.` instead of `zelix`).
These should generall just be your second choice. The first choice of the detect feature and in general is to use transformers not in such sub-packages.

Another edit: Asyou can see the `\` in the file name, this was supposed to be in an extra folder named "generated", but apparantly file separator was hardcoded.

**Comment by f4r2** [comment]
ty
