### ISSUE TITLE
Help me!!!! to deobfuscate with allatori

### ISSUE THREAD

**Issue by nocturno4115** [java-deobfuscator/deobfuscator#981]
Can you help me to deobfuscate this file who has obfuscate with allatori

[jar + libs](https://drive.google.com/file/d/1KR_dWt3I_iOmjUNgUVEiOppaEslmddLF/view?usp=sharing)

**Comment by Janmm14** [comment]
The content you linked has been removed by google due to violation of their terms & services.

WE DO NOT SUPPORT CRACKING (or leaking) APPLICATIONS HERE. We have PINNED issue #653 to not upload or link anything where you do not have the right to PUBLISH / SHARE.

The repository was in danger of getting deleted due to DMCA multiple times!
